<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKFBLbd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKFBLbd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCKFBLbd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCKFBLbd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCKFBLbd\App_KernelDevDebugContainer([
    'container.build_hash' => 'CKFBLbd',
    'container.build_id' => '2bc655c8',
    'container.build_time' => 1739362258,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKFBLbd');
