<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRsVHWlx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRsVHWlx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRsVHWlx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRsVHWlx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRsVHWlx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RsVHWlx',
    'container.build_id' => '6124d54d',
    'container.build_time' => 1739448353,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRsVHWlx');
